version: 2.1
orbs:
  android: circleci/android@2.0.3
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/android
    steps:
      - android/start-emulator-and-run-tests
workflows:
  example-workflow:
    jobs:
      - example-job