version: 2.1

orbs:
  android: circleci/android@1.0.3
  gcp-cli: circleci/gcp-cli@2.2.0

jobs:
  unit-test:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew testDebug
      - android/save-gradle-cache
      - android/save-build-cache
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  android-test:
    parameters:
      system-image:
        type: string
        default: system-images;android-30;google_apis;x86
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout
      
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: << parameters.system-image >>
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/outputs/androidTest-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  debug-build:
    executor:
      name: android/android-machine
      resource-class: xlarge
    steps:
      - checkout

      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew

      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble debug build
          command: |
            ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/release/app-debug.apk
      - store_artifacts:
          path: ui_favorites/build/outputs/apk/debug/ui_favorites-debug.apk

workflows:
  test-and-build:
    jobs:
      - unit-test
      - android/run-ui-tests
      - android-test:
          matrix:
            alias: android-test-all
            parameters:
              system-image:
                - system-images;android-30;google_apis;x86
          name: android-test-<<matrix.system-image>>
      - debug-build:
          requires:
            - unit-test
            - android-test-all

