version: 2.1
 
orbs:
  android: circleci/android@1.0.3
 
jobs:
  build:
    executor: android/android-machine
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results

      - run:
          name: Run Core Module Unit Tests
          command: ./gradlew :core:test
      - store_artifacts:
          path: core/build/reports
      - store_test_results:
          path: core/build/test-results

      - run:
          name: Run Data Module Unit Tests
          command: ./gradlew :data:test
      - store_artifacts:
          path: data/build/reports
      - store_test_results:
          path: data/build/test-results

      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file